name: Auto-approve Renovate PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'renovate[bot]' }}
    
    steps:
      - name: Wait for all checks to complete
        uses: lewagon/wait-on-check-action@v1.4.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          running-workflow-name: 'auto-approve'

      - name: Auto-approve after all checks pass
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.AUTO_APPROVE_PAT || secrets.GITHUB_TOKEN }}
          review-message: |
            Auto-approving Renovate PR after all CI checks passed ✅
            
            This approval enables automerge for dependency updates. 