name: Auto-approve Renovate PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'renovate[bot]' }}
    
    steps:
      - name: Wait for all checks to complete
        uses: lewagon/wait-on-check-action@v1.4.0
        id: wait-for-checks
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          running-workflow-name: 'auto-approve'

      - name: Debug check status
        run: |
          echo "Check status: ${{ steps.wait-for-checks.outcome }}"
          echo "All outputs: ${{ toJson(steps.wait-for-checks.outputs) }}"

      - name: Auto-approve ONLY if all checks pass
        if: ${{ steps.wait-for-checks.outcome == 'success' }}
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          review-message: |
            Auto-approving Renovate PR after all CI checks passed ✅
            
            Check status: ${{ steps.wait-for-checks.outcome }}
            This approval enables automerge for dependency updates.

      - name: Comment if checks failed
        if: ${{ steps.wait-for-checks.outcome != 'success' }}
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ Auto-approval skipped - Some CI checks failed or are incomplete.\n\nCheck status: ${{ steps.wait-for-checks.outcome }}'
            }); 